# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Checklayer — QA as a Service
email: contact@checklayer.io
description: >- # this means to ignore newlines until "baseurl:"
  Fast, reliable Quality Assurance for your web and mobile products. 
  We provide tailored QA solutions for startups, small businesses, and indie developers 
  to catch bugs before your users do. Ship with confidence!
baseurl: "" # the subpath of your site, e.g. /blog (leave empty if no subpath)
url: "https://shaban-qa.github.io" # the base hostname & protocol for your site
twitter_username: checklayer # replace with your actual Twitter handle if you have one
github_username: checklayer # replace with your actual GitHub username if applicable

# Build settings
theme: minima # you can change this to another theme if you prefer (e.g., "architect", "cayman")
plugins:
  - jekyll-feed # adds RSS feed support
  - jekyll-seo-tag # improves SEO (optional, add gem to Gemfile if you use this)

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
