title: Checklayer — QA as a Service
email: contact@checklayer.io
description: >-
  Fast, reliable Quality Assurance for your web and mobile products.  We provide
  tailored QA solutions for startups, small businesses, and indie developers  to
  catch bugs before your users do. Ship with confidence!
baseurl: ''
url: 'http://localhost:4000'
twitter_username: checklayer
github_username: checklayer
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin
jekyll_admin:
  api_path: admin/api
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
